Write a python program to perform matrix operations on an M x N matrix and solve a system of linear equations. Use inbuilt functions to implement the operations. Get two matrices from the user. The program should support the following Menus,

1. Matrix Addition
2. Matrix Subtraction
3. Scalar Matrix Multiplication
4. Elementwise Matrix Multiplication
5. Matrix Multiplication
6. Matrix Transpose
7. Trace of a Matrix
8. Solve System of Linear Equations
9. Determinant
10. Inverse
11. Eigen Value and Eigen Vector
12. Exit


In [190]:
import numpy as np

#1. Matrix Addition
def add_matrices(arr1, arr2):
    return np.add(arr1, arr2)

#2. Matrix Subtraction
def sub_matrices(arr1, arr2):
    return np.subtract(arr1, arr2)

# 3. Scalar Matrix Multiplication
def scalar_mul(arr, k):
    return arr*k

# 4. Elementwise Matrix Multiplication
def element_wise_mul(arr1, arr2):
    mat1 = np.array(arr1)
    mat2 = np.array(arr2)
    mul = mat1*mat2

    return mul 

# 5. Matrix Multiplication
def matrix_mul(arr1, arr2):
    return np.dot(arr1, arr2)

# 6. Matrix Transpose
def matrix_transpose(arr):
    return np.transpose(arr)

# 7. Trace of a Matrix
def matrix_trace(arr):
    return np.trace(arr)

# 8. Solve System of Linear Equations
def sol_matrix(X, Y):
    return np.linalg.solve(X, Y)

# 9. Determinant
def det_matrix(arr):
    return np.linalg.det(arr)

# 10. Inverse
def inv_matrix(arr):
    return np.linalg.inv(arr)

#11. Eigen Value and Eigen Vector
def eigen_matrix(arr):
    return np.linalg.eig(arr)

#Taking input
def input_arr(r, c):
    mat = []
    for i in range(r):
        row = list(map(float, input().split()))
        if len(row) != c:
            print(f"Error: You must enter exactly {c} elements.")
        else:
            mat.append(row)
            
        #mat.append(row)
    
    return np.mat(mat)


In [206]:
choice = -1

while choice != 0:

    print("\n1. Add two matrices")
    print("\n2. Subtract two matrices")
    print("\n3. Scalar Matrix Multiplication")
    print("\n4. Elementwise Matrix Multiplication")
    print("\n5. Matrix Multiplication")
    print("\n6. Matrix Transpose")
    print("\n7. Trace of a Matrix")
    print("\n8. Solve System of Linear Equations")
    print("\n9. Determinant")
    print("\n10. Inverse")
    print("\n11. Eigen values and Eigen vectors")
    print("\n12. Exit")
    
    choice = int(input("Enter your choice"))
    
    if choice == 1:
        r1 = int(input("Enter no of rows for first matrix:"))
        r2 = int(input("Enter no of rows for second matrix:"))
        
        if r1 != r2:
            print("No of rows should be equal")
            continue
            
        c1 = int(input("Enter no of columns for first matrix:"))
        c2 = int(input("Enter no of columns for second matrix:"))

        if c1 != c2:
            print("No of columns should be equal")
            continue
        
        
        arr1 = []
        arr2 = []
        
        print("Enter elements of the first matrix row by row:\n")
        arr1 = input_arr(r1, c1)
        print("First matrix:\n", arr1)
        
        print("Enter elements of the second matrix row by row:\n")        
        arr2 = input_arr(r2, c2)
        print("Second matrix:\n", arr2)

        print("Addition of the two matrices:\n", add_matrices(arr1, arr2))

    elif choice == 2:
        r1 = int(input("Enter no of rows for first matrix:"))
        r2 = int(input("Enter no of rows for second matrix:"))
        
        if r1 != r2:
            print("No of rows should be equal")
            continue
            
        c1 = int(input("Enter no of columns for first matrix:"))
        c2 = int(input("Enter no of columns for second matrix:"))

        if c1 != c2:
            print("No of columns should be equal")
            continue
        
        
        arr1 = []
        arr2 = []
        
        print("Enter elements of the first matrix row by row:\n")
        arr1 = input_arr(r1, c1)
        print("First matrix:\n", arr1)
        
        print("Enter elements of the second matrix row by row:\n")        
        arr2 = input_arr(r2, c2)
        print("Second matrix:\n", arr2)

        print("Subtraction of the two matrices:\n", sub_matrices(arr1, arr2))

    elif choice == 3:
        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []

        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("Scalar multiplication:\n", scalar_mul(arr, k))
        
    elif choice == 4:
        
        r1 = int(input("Enter no of rows for first matrix:"))
        r2 = int(input("Enter no of rows for second matrix:"))
        
        if r1 != r2:
            print("No of rows should be equal")
            continue
            
        c1 = int(input("Enter no of columns for first matrix:"))
        c2 = int(input("Enter no of columns for second matrix:"))

        if c1 != c2:
            print("No of columns should be equal")
            continue
        
        
        arr1 = []
        arr2 = []
        
        print("Enter elements of the first matrix row by row:\n")
        arr1 = input_arr(r1, c1)
        print("First matrix:\n", arr1)
        
        print("Enter elements of the second matrix row by row:\n")        
        arr2 = input_arr(r2, c2)
        print("Second matrix:\n", arr2)

        print("Elementwise Matrix multiplication of the two matrices:\n", element_wise_mul(arr1, arr2))

    elif choice == 5:

        r1 = int(input("Enter no of rows for first matrix:"))
        r2 = int(input("Enter no of rows for second matrix:"))
            
        c1 = int(input("Enter no of columns for first matrix:"))
        c2 = int(input("Enter no of columns for second matrix:"))

        if c1 != r2:
            print("Invalid inputs\n")
            continue
        
        
        arr1 = []
        arr2 = []
        
        print("Enter elements of the first matrix row by row:\n")
        arr1 = input_arr(r1, c1)
        print("First matrix:\n", arr1)
        
        print("Enter elements of the second matrix row by row:\n")        
        arr2 = input_arr(r2, c2)
        print("Second matrix:\n", arr2)

        print("Matrix Multiplication of the two matrices:\n", matrix_mul(arr1, arr2))

    elif choice == 6:

        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        #k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []
        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("The matrix is:\n", arr)
        print("Transpose of the matrix:\n", matrix_transpose(arr))

    elif choice == 7:

        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        #k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []
        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("The matrix is:\n", arr)
        print("Trace of the matrix:\n", matrix_trace(arr))

    elif choice == 8:

        n = int(input("Enter no of equations:"))
        print("Enter the system of equations' co-efficients line by line:")
        sys =[]

        for i in range(n):
            row = list(map(float, input().split()))
            sys.append(row)
            
        mat = np.array(sys)
        A = mat[:, : -1]
        b = mat[:, -1].reshape(len(sys), 1)
        print("System of equations in form of Ax = b:\n")
        print("A is:\n", A)
        print("b is:\n", b)
        print("Solution of the system of equations is:", sol_matrix(A, b))

    elif choice == 9:

        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        #k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []
        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("The matrix is:\n", arr)
        print("Determinant of the matrix:\n", det_matrix(arr))
        
    elif choice == 10:

        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        #k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []
        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("The matrix is:\n", arr)
        if det_matrix(arr) == 0:
            print("Inverse for the matrix does not exist\n")
            continue
        print("Inverse of the matrix:\n", inv_matrix(arr))

    elif choice == 11:

        r = int(input("Enter no of rows:"))
        c = int(input("Enter no of columns:"))
        #k = int(input("Enter the number to perform scalar multiplication:"))
        arr = []
        print("Enter elements of the matrix row by row:\n")
        arr = input_arr(r, c)
        print("The matrix is:\n", arr)
        eigen_values, eigen_vectors = eigen_matrix(arr)
        print("Eigen values of the matrix:\n", eigen_values)
        print("Eigen values of the matrix:\n", eigen_vectors)

    elif choice == 12:

        print("Exiting.....\n")
        choice = 0

    else:
        print("Invalid input\n")
        continue


1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 1
Enter no of rows for first matrix: 3
Enter no of rows for second matrix: 3
Enter no of columns for first matrix: 3
Enter no of columns for second matrix: 3


Enter elements of the first matrix row by row:



 1 2 3
 4 5 6
 7 8 9


First matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Enter elements of the second matrix row by row:



 1 2 3
 4 5 6
 7 8 9


Second matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Addition of the two matrices:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 2
Enter no of rows for first matrix: 3
Enter no of rows for second matrix: 3
Enter no of columns for first matrix: 3
Enter no of columns for second matrix: 3


Enter elements of the first matrix row by row:



 1 4 9
 12 4 7
 11 11 11


First matrix:
 [[ 1.  4.  9.]
 [12.  4.  7.]
 [11. 11. 11.]]
Enter elements of the second matrix row by row:



 1 2 3
 4 5 6
 7 8 9


Second matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Subtraction of the two matrices:
 [[ 0.  2.  6.]
 [ 8. -1.  1.]
 [ 4.  3.  2.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 3
Enter no of rows: 3
Enter no of columns: 3
Enter the number to perform scalar multiplication: 4


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


Scalar multiplication:
 [[ 4.  8. 12.]
 [16. 20. 24.]
 [28. 32. 36.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 4
Enter no of rows for first matrix: 3
Enter no of rows for second matrix: 3
Enter no of columns for first matrix: 3
Enter no of columns for second matrix: 3


Enter elements of the first matrix row by row:



 1 2 3
 4 5 6
 7 8 9


First matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Enter elements of the second matrix row by row:



 1 2 3
 4 5 6
 7 8 9


Second matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Elementwise Matrix multiplication of the two matrices:
 [[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 5
Enter no of rows for first matrix: 3
Enter no of rows for second matrix: 3
Enter no of columns for first matrix: 3
Enter no of columns for second matrix: 3


Enter elements of the first matrix row by row:



 1 2 3
 4 5 6
 7 8 9


First matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Enter elements of the second matrix row by row:



 1 2 3
 4 5 6
 7 8 9


Second matrix:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Matrix Multiplication of the two matrices:
 [[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 6
Enter no of rows: 3
Enter no of columns: 3


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


The matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Transpose of the matrix:
 [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 7
Enter no of rows: 3
Enter no of columns: 3


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


The matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Trace of the matrix:
 15.0

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 8
Enter no of equations: 3


Enter the system of equations' co-efficients line by line:


 2 3 -1 1
 -3 -1 2 -2
 1 2 3 3


System of equations in form of Ax = b:

A is:
 [[ 2.  3. -1.]
 [-3. -1.  2.]
 [ 1.  2.  3.]]
b is:
 [[ 1.]
 [-2.]
 [ 3.]]
Solution of the system of equations is: [[ 1.25]
 [-0.25]
 [ 0.75]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 9
Enter no of rows: 3
Enter no of columns: 3


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


The matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Determinant of the matrix:
 -9.51619735392994e-16

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 10
Enter no of rows: 3
Enter no of columns: 3


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


The matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Inverse of the matrix:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 11
Enter no of rows: 3
Enter no of columns: 3


Enter elements of the matrix row by row:



 1 2 3
 4 5 6
 7 8 9


The matrix is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Eigen values of the matrix:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigen values of the matrix:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

1. Add two matrices

2. Subtract two matrices

3. Scalar Matrix Multiplication

4. Elementwise Matrix Multiplication

5. Matrix Multiplication

6. Matrix Transpose

7. Trace of a Matrix

8. Solve System of Linear Equations

9. Determinant

10. Inverse

11. Eigen values and Eigen vectors

12. Exit


Enter your choice 12


Exiting.....

